config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'sign-in' => 'devise/sessions#new'
    get 'sign-out' => 'devise/sessions#destroy'
    get 'sign-up' => 'devise/registrations#new'
  end

  namespace :admin do
    resources :posts, :users, :comments, :articles
  end

  resources :comments, :posts, :articles

  get 'post/:post_id/comments' => 'comments#index', post_id: nil, as:'post_comments'
  get 'article/:article_id/comments' => 'comments#index', article_id: nil, as:'article_comments'
  get 'tags/:resource_type/:name' => 'tags#index', as: 'tags'

  root to: 'posts#index'
end

app/views/layouts/shared/_header.html.slim
header.intro-header style=("background-image: url('#{asset_path('home-bg.jpg') }')")
  .container
    .row
      .col-lg-12.col-lg-offset-0.col-md-12.col-md-offset-0
        .site-heading
          h1= link_to site_title, root_path
          hr.small/
          span.subheading= site_description

app/views/layouts/shared/_nav.html.slim
nav.navbar.navbar-default.navbar-custom.navbar-fixed-top
  .container-fluid
    .navbar-header.page-scroll
      - if current_user
        = link_to 'Admin', admin_posts_path, class: 'navbar-brand'
      - else
        = link_to 'Sign in', sign_in_path, class: 'navbar-brand'
    ul.nav.navbar-nav.navbar-right
      li= link_to 'Home', root_path
      li= link_to 'Posts', posts_path
      li= link_to 'Articles', articles_path
      - if current_user
        li= link_to 'Sign out', sign_out_path