config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'sign-in' => 'devise/sessions#new'
    get 'sign-out' => 'devise/sessions#destroy'
    get 'sign-up' => 'devise/registrations#new'
  end

  namespace :admin do
    resources :posts, :users, :comments, :articles
  end

  resources :comments, :posts, :articles

  get 'post/:post_id/comments' => 'comments#index', post_id: nil, as:'post_comments'
  get 'article/:article_id/comments' => 'comments#index', article_id: nil, as:'article_comments'
  get 'tags/:resource_type/:name' => 'tags#index', as: 'tags'

  root to: 'posts#index'
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  include Taggable
  include Commentable

  belongs_to :user, inverse_of: :articles

  validates :user_id, presence: true
  validates :title, presence: true
  validates :body, presence: true

  default_scope -> { order('created_at DESC') }

  friendly_id :title, use: :slugged
  paginates_per 10

  def author_name
    user.try(:name)
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.order('created_at DESC').page(params[:page])
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @article.save
        format.html { redirect_to admin_article_path(@article), notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params.merge(user_id: current_user.id))
        format.html { redirect_to admin_article_path(@article), notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

  private
  def set_article
    @article = Article.friendly.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :tag_names)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]

  def index
    @articles = Article.order('created_at DESC').page(params[:page])
  end

  def show
    @title = @article.title
  end

  private
  def set_article
    @article = Article.friendly.find(params[:id])
  end
end

app/views/admin/articles/_form.html.slim
= form_for [:admin, @article] do |f|
  fieldset
    - if @article.errors.any?
      #error_explanation
        h2 = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
        ul
          - @article.errors.full_messages.each do |message|
            li = message

    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :tags
      = f.text_field :tag_names, class: 'form-control', placeholder: 'Enter tags separated by a comma (,)'
    .form-group
      = f.label :body
      = f.text_area :body, class: 'form-control'
  = f.submit 'Submit', class: 'btn btn-primary'

app/views/admin/articles/edit.html.slim
h2 Editing article

== render 'form'

= link_to 'Show', @article, target: '_blank'
'|
= link_to 'Back', admin_articles_path

app/views/admin/articles/index.html.slim
.row
  .col-xs-6= render 'admin/shared/nav'
  .col-xs-6

.row
  .col-xs-8
    h2.admin-title Listing articles
  .col-xs-4
    .create-action= link_to 'Create a new article', new_admin_article_path, class: 'pull-xs-right btn btn-primary'

.row
  .col-xs-12
    table.table.table-hover
      thead.thead-inverse
        tr
          th Title
          th Date Created
          th
          th
          th

      tbody
        - @articles.each do |article|
          tr
            td = article.title
            td = local_time article.created_at
            td = link_to 'Show', admin_article_path(article)
            td = link_to 'Edit', edit_admin_article_path(article)
            td = link_to 'Destroy', admin_article_path(article), data: { confirm: 'Are you sure?' }, method: :delete

.row
  .col-xs-12
    = raw paginate(@articles)

app/views/admin/articles/new.html.slim
h2 New article

== render 'form'

br
= link_to 'Back', admin_articles_path

app/views/admin/articles/show.html.slim
h1=@article.title

.tags= tag_links('articles', @article.tag_names).html_safe

= to_html @article.body

= link_to 'Edit', edit_admin_article_path(@article)
'|
= link_to 'Back', admin_articles_path