config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'sign-in' => 'devise/sessions#new'
    get 'sign-out' => 'devise/sessions#destroy'
    get 'sign-up' => 'devise/registrations#new'
  end

  namespace :admin do
    resources :posts, :users, :comments, :articles
  end

  resources :comments, :posts, :articles

  get 'post/:post_id/comments' => 'comments#index', post_id: nil, as:'post_comments'
  get 'article/:article_id/comments' => 'comments#index', article_id: nil, as:'article_comments'
  get 'tags/:resource_type/:name' => 'tags#index', as: 'tags'

  root to: 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  include Taggable
  include Commentable

  belongs_to :user, inverse_of: :posts

  validates :user_id, presence: true
  validates :title, presence: true
  validates :body, presence: true

  default_scope -> { order('created_at DESC') }

  friendly_id :title, use: :slugged
  paginates_per 10

  def author_name
    user.try(:name)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.order('created_at DESC').page(params[:page])
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_post_path(@post), notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params.merge(user_id: current_user.id))
        format.html { redirect_to admin_post_path(@post), notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

  private
  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :tag_names)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  def index
    @posts = Post.order('created_at DESC').page(params[:page])
  end

  def show
    @title = @post.title
  end

  private
  def set_post
    @post = Post.friendly.find(params[:id])
  end
end

app/views/admin/posts/_form.html.slim
= form_for [:admin, @post] do |f|
  fieldset
    - if @post.errors.any?
      #error_explanation
        h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
        ul
          - @post.errors.full_messages.each do |message|
            li = message

    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :tags
      = f.text_field :tag_names, class: 'form-control', placeholder: 'Enter tags separated by a comma (,)'
    .form-group
      = f.label :body
      = f.text_area :body, class: 'form-control'
  = f.submit 'Submit', class: 'btn btn-primary'

app/views/admin/posts/edit.html.slim
h2 Editing post

== render 'form'

= link_to 'Show', @post, target: '_blank'
'|
= link_to 'Back', admin_posts_path

app/views/admin/posts/index.html.slim
.row
  .col-xs-6= render 'admin/shared/nav'
  .col-xs-6

.row
  .col-xs-8
    h2.admin-title Listing posts
  .col-xs-4
    .create-action= link_to 'Create a new post', new_admin_post_path, class: 'pull-xs-right btn btn-primary'

.row
  .col-xs-12
    table.table.table-hover
      thead.thead-inverse
        tr
          th Title
          th Date Created
          th
          th
          th

      tbody
        - @posts.each do |post|
          tr
            td = post.title
            td = local_time post.created_at
            td = link_to 'Show', admin_post_path(post)
            td = link_to 'Edit', edit_admin_post_path(post)
            td = link_to 'Destroy', admin_post_path(post), data: { confirm: 'Are you sure?' }, method: :delete

.row
  .col-xs-12
    = raw paginate(@posts)

app/views/admin/posts/new.html.slim
h2 New post

== render 'form'

br
= link_to 'Back', admin_posts_path

app/views/admin/posts/show.html.slim
h1=@post.title

.tags= tag_links('posts', @post.tag_names).html_safe

= to_html @post.body

= link_to 'Edit', edit_admin_post_path(@post)
'|
= link_to 'Back', admin_posts_path