config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'sign-in' => 'devise/sessions#new'
    get 'sign-out' => 'devise/sessions#destroy'
    get 'sign-up' => 'devise/registrations#new'
  end

  namespace :admin do
    resources :posts, :users, :comments, :articles
  end

  resources :comments, :posts, :articles

  get 'post/:post_id/comments' => 'comments#index', post_id: nil, as:'post_comments'
  get 'article/:article_id/comments' => 'comments#index', article_id: nil, as:'article_comments'
  get 'tags/:resource_type/:name' => 'tags#index', as: 'tags'

  root to: 'posts#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, inverse_of: :user
  has_many :posts, inverse_of: :user

  validates :first_name, presence: true
  validates :last_name, presence: true

  paginates_per 7

  devise :database_authenticatable, :confirmable, :lockable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  default_scope -> { order('last_name ASC') }

  def name
    [first_name, last_name].join(' ')
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :destroy]

  def index
    @users = User.order('last_name ASC').page(params[:page])
  end

  def show
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.slim
h2 Listing users

table.table.table-hover
  thead.thead-inverse
    tr
      th Name
      th Email
      th

  tbody
    - @users.each do |admin_user|
      tr
        td= admin_user.name
        td= admin_user.email
        td = link_to 'Destroy', admin_user_path(admin_user), data: { confirm: 'Are you sure?' }, method: :delete

= paginate @users

app/views/admin/users/show.html.slim
p#notice = notice


= link_to 'Edit', edit_admin_user_path(@user)
'|
= link_to 'Back', admin_users_path